name: pdc_wallet
description: A dart Bitcoin library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.0.2
homepage: https://github.com/pdc-flutter
author: JUS <ragislam@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  bip39: ^1.0.3
  bip32: ^1.0.5
  pointycastle: ^1.0.2
  hex: ^0.1.2
  bs58check: ^1.0.1
  meta: ^1.2.3
  bech32: 0.1.2
  pdcBech32:
    git:
      url: https://github.com/pdc-flutter/pdcBech32.git
      ref: main

dev_dependencies:
  test: ^1.15.4
